### ISSUE TITLE
`continueOnAssertionFailure` doesn't return the information of the assertions

### ISSUE THREAD

**Issue by Stipci** [Qytera-Gmbh/QTAF#183]
While setting up qtaf to continue on Assertion Failure, the user can't see which assertion leads to the error.

The output on the console shows no failures and in the html report the error message is missing. But information is not totally lost. In the Json-Report the message of the Assertion is shown. The status of the report is marked as an failure.

Console Output: Continue on Assertion= false
![Console_continue_false](https://github.com/Qytera-Gmbh/QTAF/assets/94533221/93f7933d-bc40-48df-a24e-d22a15c587ac)

Console Output: Continue on Assertion= true
![Console_continue_true](https://github.com/Qytera-Gmbh/QTAF/assets/94533221/7ee7de16-5be8-4e16-bdb4-6ee99de59d75)

Report-HTML: Continue on Assertion= true
![Report_continue_true](https://github.com/Qytera-Gmbh/QTAF/assets/94533221/762ebff1-0428-4a2a-b806-5e4fdebbc0ee)

JSON-Report:  Continue on Assertion= true
![Json-Report_continue_true](https://github.com/Qytera-Gmbh/QTAF/assets/94533221/a8f9efcc-5f1a-4088-a003-28570e39ba27)

**Comment by qytera-development** [comment]
Assertions are now logged to the console. Also failed assertions now lead to failed test cases.
