### ISSUE TITLE
HTML report can't be deactivated

### ISSUE THREAD

**Issue by Stipci** [Qytera-Gmbh/QTAF#185]
The following setting doesn't have any effect. The HTML report is always generated after each run.

```json
"htmlReport": {
  "enabled": false
}
```

**Comment by qytera-development** [comment]
We need to implement a check whether the value `htmlReport.enabled` is set to true in the `CreateReportSubscriber` class of the html report plugin.

If no value is set in the configuration file we assume that no html report should be created.
