### ISSUE TITLE
Errormessage is not shown in the HTML-Report

### ISSUE THREAD

**Issue by Stipci** [Qytera-Gmbh/QTAF#190]
while the continueOnAssertionFailure is set to true the HTML-Report don't show the error message of an assertion.

This screenshot
![Screenshot 2023-09-08 140130](https://github.com/Qytera-Gmbh/QTAF/assets/94533221/97470ea2-28ac-43dd-9152-ae0f61f74f36)

has no errormessage. In the json-report is the assertion message set up as an message

"status": "ERROR",
              "start": "Sep 8, 2023, 1:38:08 PM",
              "end": "Sep 8, 2023, 1:40:30 PM",
              "duration": 0,
              "assertions": [
                {
                  "type": "ASSERT_TRUE",
                  "status": "FAILED",
                  "condition": false,
                  "error": {},
                  "level": "INFO",
                  "message": "The Services : In-Memory DB / Spreadsheet Server / Web Frontend / Web Backend / Integrator / failed to be started",
                  "featureId": "com.jedox.tests.ChooseInstanceTests",
                  "abstractScenarioId": "com.jedox.tests.ChooseInstanceTests.restartTheServices",
                  "scenarioId": "com.jedox.tests.ChooseInstanceTests.restartTheServices-a07a939c-dea5-4427-a9a9-c0f608640fc1"
                }
              ],

**Comment by qytera-development** [comment]
This problem was solved in Release v0.2.11
