### ISSUE TITLE
Testrail doesn't get a screenshot of the failed test

### ISSUE THREAD

**Issue by Stipci** [Qytera-Gmbh/QTAF#191]
Actually testrail only get the status failed of a test run. The Screenshot is not sent to testrail.

The customer wants in addition the HTML-Report sent to testrail.

**Comment by csvtuda** [comment]
The issue should be fixed in version `0.2.8`.

**Comment by MoritzSalein** [comment]
It is included in release https://github.com/Qytera-Gmbh/QTAF/releases/tag/v0.2.8
