### ISSUE TITLE
It should be possible to make screenshots of elements

### ISSUE THREAD

**Issue by qytera-development** [Qytera-Gmbh/QTAF#204]
There should be a method named "screenhots" in the test context that accepts a selector and makes a screenshot of an element. The screenshot should be saved in the log directory and also in the JSON log file.

**Comment by MoritzSalein** [comment]
@qytera-development Could you define more details of this feature request? 
Do you want to screenshot the selector or the area of the selector and all elements ins this space? 
For example: You want to screenshot a button element, where you can see a sub element of a small icon and a text? Or must it be switchable?

**Comment by OliverHoenig** [comment]
Due to inactivity, I will close this issue now.
