### ISSUE TITLE
Report.json is missing the error message

### ISSUE THREAD

**Issue by qytera-development** [Qytera-Gmbh/QTAF#210]
In the report.json file the error message is missing. If a step fails I would like to find the error message in the corresponding step object.

**Comment by qytera-development** [comment]
This bug has been fixed in the PR https://github.com/Qytera-Gmbh/QTAF/pull/214
It will be part of the next version 0.2.8

**Comment by OliverHoenig** [comment]
This bug has been worked on. It is now fixed in version 0.2.8.
