### ISSUE TITLE
In Xray the error message should be uploaded to the corresponding step

### ISSUE THREAD

**Issue by qytera-development** [Qytera-Gmbh/QTAF#211]
In Xray I want to see the error message if a step fails. The current status is that the step is only marked as failed, but currently we cannot see the reason why it failed.

The step should look like this if it has an error:

```console
click button

ERROR:
<exception text here>
```

**Comment by csvtuda** [comment]
Addressed in #212.

**Comment by OliverHoenig** [comment]
This feature has been worked on. It is now implemented in version 0.2.8.
