### ISSUE TITLE
Configuration parameters are not read in version `0.2.7`

### ISSUE THREAD

**Issue by Stipci** [Qytera-Gmbh/QTAF#222]
i have set up additional parameters in qtaf.json. 

```
	"page": {
		"url": "https://console-qtaf.cloud.REDACTED.com/",
		"instance": "live-qtaf.cloud.REDACTED.com",
		"user": "REDACTED",
		"password": "REDACTED"
	},
```

I'm trying to read this in my code with config.getString("page.instance", "NO_CHANGE").

Now i'm getting always the "NO_CHANGE"

**Comment by csvtuda** [comment]
Cannot reproduce in version `0.2.7`. The following line prints the expected value:

```java
System.out.println(config.getString("page.instance", "NO_CHANGE"));
// live-qtaf.cloud.REDACTED.com
```

**Comment by OliverHoenig** [comment]
After consultation with @Stipci, it could be confirmed that it was a different problem, which has been fixed and no longer exists.
