### ISSUE TITLE
Could not upload html report 

### ISSUE THREAD

**Issue by mzdih** [Qytera-Gmbh/QTAF#248]
I attempted to run some basic test cases, such as logging, and then uploading the results (the HTML file), but I couldn't find the report in Xray

**Comment by qytera-development** [comment]
First you need to activate the scenario evidence upload in qtaf.json. Set the values of `xray.enabled`, `xray.resultsUpload.scenarioReportEvidence` and `xray.resultsUpload.scenarioImageEvidence` to `true`.
Next activate scenario evidence upload in your XrayTest annotation like in the following example:

```java
@XrayTest(key = "TEST-001", scenarioReport = true, screenshots = true)
public void testOne() {
}
```

**Comment by qytera-development** [comment]
It seems like this feature currently only works with test cases that do not use data loaders

**Comment by qytera-development** [comment]
The bug is now fixed. Use the new version v0.2.10 that contains the fix for this bug.
