### ISSUE TITLE
Qtaf Assertions Titel

### ISSUE THREAD

**Issue by mzdih** [Qytera-Gmbh/QTAF#260]
I noticed that after using **QtAF Assertions**, the generated HTML report lacks a title for the assertion. Moreover, the message is displayed in both failed and successful cases. It is important to document that the message should be formulated for use in both scenarios. As a workaround, we can use the message as a title for the assertion in the report

![assertionTitel](https://github.com/Qytera-Gmbh/QTAF/assets/115978718/dd2cc990-d169-4a04-8b3b-aedfb98acdd4)

**Comment by qytera-development** [comment]
The messages for assertions should be as neutral as possible, for example "Expected delivery point to be visible". Currently there is no option for passing two different messages to an assertion.

**Comment by qytera-development** [comment]
The problem with the missing title was solved in release v0.2.11
