### ISSUE TITLE
API Testing does not run together with HTML Report

### ISSUE THREAD

**Issue by MoritzSalein** [Qytera-Gmbh/QTAF#264]
API Testing does not run together with HTML Report. I get error output in the console, as of illigal characters.
Sample output:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.2:test (default-test) on project API_QTAF: 
[ERROR]
[ERROR] Please refer to C:\Projekte\Qytera\API_QTAF\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] Illegal char <>> at index 137: C:\Projekte\Qytera\API_QTAF\logs\2024-03-05\15-48-20-firefox-688f2f39-8d08-4f4f-8d8b-75957dce5395\scenario_Login-Test statusCodeIs(200) -> expect a logMessage that indicates PASSED.html
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] Illegal char <>> at index 137: C:\Projekte\Qytera\API_QTAF\logs\2024-03-05\15-48-20-firefox-688f2f39-8d08-4f4f-8d8b-75957dce5395\scenario_Login-Test statusCodeIs(200) -> expect a logMessage that indicates PASSED.html
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:631)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
...
`

**Comment by OliverHoenig** [comment]
The feature was still in the design phase. The approach followed there for API testing will not be pursued further. A different approach to implementing API tests using QTAF is being considered. 
As this issue relates to the old approach, which is now no longer being pursued, the issue is closed.
