### ISSUE TITLE
Assertions in tests cannot be tracked for Xray upload

### ISSUE THREAD

**Issue by vladaaz** [Qytera-Gmbh/QTAF#268]
If I write an assertion into a method with the annotation "@Test" and inside the method e.g. assertTrue(....) then the entire Xray report is not uploaded. I get this response from Xray-API: "{}".

That's how my logs look like:
[QTAF Xray Plugin] Failed to import test execution: 400 Bad Request: {"error":"There were 2 validation errors when trying to create the test steps."}
 [QTAF Xray Plugin] Uploaded test execution. Key is null
 
 I don't receive a key to look into the executions in Xray.

**Comment by MoritzSalein** [comment]
Two additional question to this issue:
1. In the most examples of our documentation we add several assertions directly in the @test method. Is this currently not working? I see it more as an implementation error. E.g. https://qytera-gmbh.github.io/projects/qtaf/sections/steps/New_QTAF_Project/#create-a-selenium-test-case
2. Where is the right place for an assertion? In a method with Step annotation?

**Comment by vladaaz** [comment]
1. It is working locally **but NOT in the Xray-Uploads Reports**. Means: Xray-Reports **can not be created** and **cannot be uploaded**.
2. Right, Assertions working only in a method with a Step Annotation.

**Comment by qytera-development** [comment]
This bug was fixed in version 0.2.12
