### ISSUE TITLE
Writing assertion error to the console 

### ISSUE THREAD

**Issue by MoritzSalein** [Qytera-Gmbh/QTAF#270]
Is it possible to write the assertion error to the console? 
Because it is easier to recognize console outputs during the code implementation as to look into the new generated test report.

**Comment by OliverHoenig** [comment]
The feature was still in the design phase. The approach followed there for API testing will not be pursued further. A different approach to implementing API tests using QTAF is being considered. 
As this issue relates to the old approach, which is now no longer being pursued, the issue is closed.
