### ISSUE TITLE
Html Report

### ISSUE THREAD

**Issue by mzdih** [Qytera-Gmbh/QTAF#275]
A critical issue concerns the HTML report. Occasionally, when an assertion is not linked to a specific step, it appears in the report without a title. I have also attached a screenshot illustrating this problem.

![assertionTitel](https://github.com/Qytera-Gmbh/QTAF/assets/115978718/57d4d8d2-9199-4721-aa63-edb8a44b7191)
![HtmlReportProblem](https://github.com/Qytera-Gmbh/QTAF/assets/115978718/8bf087f7-fa0b-4f6b-8814-760cf2b0a5d9)

**Comment by qytera-development** [comment]
This problem was solved in release v0.2.11
