### ISSUE TITLE
Problem in failure analysis 

### ISSUE THREAD

**Issue by mzdih** [Qytera-Gmbh/QTAF#279]
If I encounter a failure in a class that contains many test cases, as a test automation engineer, analyzing the exact location of the problem can be challenging. This difficulty is illustrated in the screenshot below, where there's a failure in CreateDeliveryPointTest.java, making it hard to determine the specific test that's causing the issue.

![image](https://github.com/Qytera-Gmbh/QTAF/assets/115978718/f8a6cf03-2410-4c4d-af8c-2d06c320e0f2)

**Comment by OliverHoenig** [comment]
Hello mzdih,

thank you for creating the ticket. To avoid misunderstandings I would ask you to answer the following questions:

- "there's a failure in CreateDeliveryPointTest.java"
What kind of error was it? Did a test case fail or is it a potential bug in QTAF that caused unwanted behaviour?
- What behaviour would you have expected from QTAF in the ideal case? 
- What would be an error handling that would have helped you in this specific case? And from your point of view, is there general potential for improvement here? If so, what would this improvement look like?

Thanks for your help.

**Comment by csvtuda** [comment]
After a brief discussion with @mzdih:

> What kind of error was it? Did a test case fail or is it a potential bug in QTAF that caused unwanted behaviour?

This is pretty much the root issue, it is very hard to identify. In both situations, the output is usually the above one.

- the steps should not be visible at all, only the messages with `[Test]`
- if provided in the annotated test method, issue IDs should appear in the `[Test]` messages (`DEV-123`, ...)
- the `[Test]` message should include the concrete method name of the test that failed
  - if the test is data-driven, the message should contain more detailed output hinting at the concrete parameters used

Propsed suggestions:
- a logging level flag might solve a few of these issues

**Comment by OliverHoenig** [comment]
Thank you very much. The issue is now being worked on.

**Comment by OliverHoenig** [comment]
There was also a request to log the XratTestDI if a test method is annotated with the Xray annotation.

**Comment by csvtuda** [comment]
Yes, this would be very helpful. I meant this when talking about issue IDs, but probably should have clarified a little bit.

**Comment by OliverHoenig** [comment]
Everything except the request to log the XrayID has been released in version #v0.2.12.
