### ISSUE TITLE
Download-Folder has to be configurable in QTaf 

### ISSUE THREAD

**Issue by mzdih** [Qytera-Gmbh/QTAF#306]
We already have an issue with the same title. What is the status of the problem? We have test cases that are blocked because of this issue. Could you provide us with an update on this matter?

**Comment by mzdih** [comment]
The proposed solution in 0.2.18 is not functioning in the Jenkins pipeline. For more information about the problem, please contact me.

**Comment by mzdih** [comment]
I have already set up a local environment in which @OliverHoenig could reproduce and analyze the problem, this was discussed and presented on 05.06, and everything was installed in his local computer

**Comment by OliverHoenig** [comment]
A fix to this issue got implementetn in Version 0.2.20
